services:
  prestashop:
    image: ghcr.io/arekflis/prestashopproject
    container_name: prestashop-klaster #will be changed
    restart: unless-stopped
    ports:
      - "19348:443"
    environment:
      DB_SERVER: mysql_193480
      DB_NAME: BE_19348
      DB_USER: root
      DB_PASSWD: student
      #DB_PORT: 3306
      PS_INSTALL_AUTO: 0
      PS_DEV_MODE: 1 
    networks:       # will be removed or changed in the final version
      - be_193480_network
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 1G
        reservations:
          cpus: "0.5"
          memory: 512M

  mysql:
    container_name: mysql_193480
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: student
      MYSQL_DATABASE: BE_19348
    networks:
      - be_193480_network
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 256M
        reservations:
          cpus: "0.25"
          memory: 256M
    
networks:
  be_193480_network: