services:
  mysql_193480:
    container_name: mysql_193480
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: student
      MYSQL_DATABASE: BE_19348
    networks:
      - be_193480_network
    volumes:
      - ./shop/scripts:/docker-entrypoint-initdb.d/
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 256M
        reservations:
          cpus: "0.25"
          memory: 256M

  prestashop:
    image: prestashop-test-klaster
    container_name: prestashop-klaster 
    restart: unless-stopped
    depends_on:
      - mysql_193480
      - memcached
    ports:
      - "19348:443"
    environment:
      DB_SERVER: mysql_193480
      DB_NAME: BE_19348
      DB_USER: root
      DB_PASSWD: student
      #DB_PORT: 3306
      PS_INSTALL_AUTO: 0
      PS_DEV_MODE: 1 
      CACHE_SYSTEM: Memcached
    networks:       
      - be_193480_network
    volumes:
      - ./shop/prestashop_data:/var/www/html
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 1G
        reservations:
          cpus: "0.5"
          memory: 512M

  memcached:
    image: memcached:latest
    container_name: memcached
    restart: unless-stopped
    networks:
      - be_193480_network
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 128M
        reservations:
          cpus: "0.25"
          memory: 64M


networks:
  be_193480_network:
