<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVoqapuz\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVoqapuz/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerVoqapuz.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerVoqapuz\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerVoqapuz\appDevDebugProjectContainer([
    'container.build_hash' => 'Voqapuz',
    'container.build_id' => 'ad0f0d2a',
    'container.build_time' => 1729702925,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVoqapuz');
