services:
  prestashop:
    image: prestashop-test-klaster #will be changed to ghcr.io image
    container_name: prestashop-klaster #will be changed
    restart: unless-stopped
    ports:
      - "19348:443"
    environment:
      DB_SERVER: admin-mysql_db
      DB_NAME: BE_19348
      DB_USER: root
      DB_PASSWD: student
      DB_PORT: 3306
      PS_INSTALL_AUTO: 0
      PS_DEV_MODE: 1 
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 1G
        reservations:
          cpus: "0.5"
          memory: 512M
    networks:       # will be removed or changed in the final version
      - external_database_test_default
networks:
  external_database_test_default:
    external: true